openapi: 3.1.0
info:
  title: Temperature Log API
  version: 0.1.0
servers:
- url: /
paths:
  /temperatures:
    get:
      operationId: listTemperatureLogs
      parameters:
      - explode: true
        in: query
        name: probe_id
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: start_at
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - explode: true
        in: query
        name: end_at
        required: false
        schema:
          format: date-time
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/TemperatureLog"
                type: array
          description: OK
      summary: Search temperature readings
    post:
      operationId: createTemperatureLog
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemperatureCreateRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemperatureLog"
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Invalid request
      summary: Register a temperature reading
  /temperatures/bulk:
    post:
      operationId: createTemperatureLogs
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemperatureCreateRequests"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/TemperatureLog"
                type: array
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Invalid request
      summary: Register multiple temperature readings
  /temperatures/latest/{probe_id}:
    get:
      operationId: getLatestTemperatureLog
      parameters:
      - explode: false
        in: path
        name: probe_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemperatureLog"
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not found
      summary: Get the latest temperature reading
components:
  schemas:
    TemperatureLog:
      example:
        recorded_at: 2000-01-23T04:56:07.000+00:00
        probe_id: probe_id
        temperature: 6.0274563
        id: 0
      properties:
        id:
          format: int64
          title: id
          type: integer
        probe_id:
          title: probe_id
          type: string
        recorded_at:
          format: date-time
          title: recorded_at
          type: string
        temperature:
          format: float
          title: temperature
          type: number
      required:
      - id
      - probe_id
      - recorded_at
      - temperature
      title: TemperatureLog
    TemperatureCreateRequest:
      example:
        recorded_at: 2000-01-23T04:56:07.000+00:00
        probe_id: probe_id
        temperature: 0.8008282
      properties:
        probe_id:
          title: probe_id
          type: string
        recorded_at:
          format: date-time
          title: recorded_at
          type: string
        temperature:
          format: float
          title: temperature
          type: number
      required:
      - probe_id
      - temperature
      title: TemperatureCreateRequest
    TemperatureCreateRequests:
      items:
        $ref: "#/components/schemas/TemperatureCreateRequest"
      title: TemperatureCreateRequests
      type: array
    ErrorResponse:
      example:
        message: message
      properties:
        message:
          title: message
          type: string
      required:
      - message
      title: ErrorResponse
